# Generated by Django 4.0.4 on 2022-06-16 08:04

from django.db import migrations, models
import django.db.models.deletion
import galleries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=galleries.models.upload_galleries_image_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', related_query_name='gallery_Q', to='products.product')),
            ],
            options={
                'verbose_name': 'تصویر محصولات',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
    ]
