# Generated by Django 4.0.4 on 2022-06-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_alter_product_title_and_more'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productgallery',
            unique_together={('image', 'product')},
        ),
    ]
