# Generated by Django 4.0.4 on 2022-06-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_category'),
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallery',
            new_name='Gallery',
        ),
    ]
