# Generated by Django 4.0.4 on 2022-06-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_productgallery_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productgallery',
            unique_together=set(),
        ),
    ]
