# Generated by Django 4.0.4 on 2022-06-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_category'),
        ('galleries', '0002_rename_productgallery_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_product', related_query_name='gallery_Q', to='products.product'),
        ),
    ]
