# Generated by Django 4.0.4 on 2022-06-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_order_alter_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
    ]
