# Generated by Django 4.0.4 on 2022-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_category'),
        ('orders', '0004_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'جزییات محصول', 'verbose_name_plural': 'اطلاعات جزییات محصولات'},
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت محصول'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orderdetail_product', to='products.product', verbose_name='محصول'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
