# Generated by Django 4.0.4 on 2022-06-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshmans'), ('SO', 'Sophomores'), ('JR', 'Juniors'), ('SR', 'Seniors'), ('GR', 'Graduates')], default='FR', max_length=2),
        ),
    ]
