# Generated by Django 4.0.4 on 2022-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_student_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_in_school_2',
            field=models.CharField(choices=[('FR', 'Freshmans'), ('SO', 'Sophomores'), ('JR', 'Juniors'), ('SR', 'Seniors'), ('GR', 'Graduates')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='fr', max_length=2),
        ),
    ]
