# Generated by Django 4.0.4 on 2022-06-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_student_year_in_school_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
