# Generated by Django 4.0.4 on 2022-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_owner_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=None, verbose_name='پرداخت شده / نشده'),
        ),
    ]
