# Generated by Django 4.0.4 on 2022-06-16 08:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'این فیلد نمی تواند خالی باشد', 'max_length': 'حداثر 150 حرف'}, help_text='اسم محصول', max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت محصول')),
                ('is_slider', models.BooleanField(default=False, verbose_name='استفاده به عنوان اسلایدر')),
                ('seen', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(blank=True, to='categorys.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['title', 'active'],
                'permissions': [('can_change_price', 'Can change price')],
                'base_manager_name': 'objects',
            },
        ),
    ]
