# Generated by Django 4.0.4 on 2022-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'objects', 'ordering': ['title', 'active'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
