# Generated by Django 4.0.4 on 2022-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'objects', 'ordering': ['title', 'active'], 'permissions': [('can_change_price', 'Can change price')], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(error_messages={'blank': 'این فیلد نمی تواند خالی باشد', 'max_length': 'حداثر 150 حرف'}, help_text='اسم محصول', max_length=150, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدید'),
        ),
    ]
