# Generated by Django 4.0.4 on 2022-06-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ip_remove_product_ip_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ip'),
        ),
    ]
