# Generated by Django 4.0.4 on 2022-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_slider',
            field=models.BooleanField(default=False, verbose_name='استفاده به عنوان اسلایدر'),
        ),
    ]
