# Generated by Django 4.0.4 on 2022-06-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_productmehtod_productmehtod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMehtod',
        ),
        migrations.CreateModel(
            name='ProductMehtod',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
