# Generated by Django 4.0.4 on 2022-06-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_productmehtod_productmehtod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMehtod',
        ),
    ]
