# Generated by Django 4.0.4 on 2022-06-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_productmehtod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_ip', to='products.ip'),
        ),
    ]
