# Generated by Django 4.0.4 on 2022-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_alter_category_options'),
        ('products', '0015_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product_category', to='categorys.category', verbose_name='دسته بندی ها'),
        ),
    ]
