# Generated by Django 4.0.4 on 2022-06-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_product_is_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('date_time_edit', models.DateTimeField(auto_now=True, verbose_name='تاریخ اصلاح')),
                ('confirmation', models.BooleanField(default=False, verbose_name='تایید شده/نشده')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='ریپلای شده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['father', 'product', 'user', 'date_time_added'],
                'base_manager_name': 'objects',
            },
        ),
    ]
