# Generated by Django 4.0.4 on 2022-06-16 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('date_time_edit', models.DateTimeField(auto_now=True, verbose_name='تاریخ اصلاح')),
                ('confirmation', models.BooleanField(default=False, verbose_name='تایید شده/نشده')),
                ('main_message', models.CharField(max_length=150, verbose_name='کامنت')),
                ('is_reply', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_c', to='comments.comment', verbose_name='ریپلای')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['date_time_added', 'date_time_edit'],
                'base_manager_name': 'objects',
            },
        ),
    ]
