# Generated by Django 4.0.4 on 2022-06-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'base_manager_name': 'objects', 'ordering': ['father', 'date_time_added'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
