# Generated by Django 4.0.4 on 2022-06-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'base_manager_name': 'objects', 'ordering': ['date_time_added'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_time_edit',
        ),
    ]
