# Generated by Django 4.0.4 on 2022-06-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_options_remove_comment_date_time_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'base_manager_name': 'objects', 'ordering': ['-reply_id'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
