# Generated by Django 4.0.4 on 2022-06-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_rename_son_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
